name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          pip install dvc
          #python train1.py
          
          echo "## Model trained" > report.md
          
